In [1]:
import numpy as np

In [2]:
arr=np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [3]:
brr=np.array([[10,20],[30,40]])
brr

array([[10, 20],
       [30, 40]])

In [9]:
arr+brr

matrix([[11, 22],
        [33, 44]])

In [4]:
arr*brr

array([[ 10,  40],
       [ 90, 160]])

In [10]:
arrm=np.matrix(arr)

In [11]:
arrm

matrix([[1, 2],
        [3, 4]])

In [12]:
brrm=np.matrix(brr)

In [13]:
brrm

matrix([[10, 20],
        [30, 40]])

In [15]:
arr*brr

matrix([[ 70, 100],
        [150, 220]])

In [ ]:
arrm