In [1]:
import numpy as np

#### By using Python loops

In [2]:
a=np.arange(1,15)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
for x in a:
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [4]:
arr=np.arange(1,13).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
for x in arr:
    for y in x:
        print(y,end="  ")
    print()

1  2  3  4  
5  6  7  8  
9  10  11  12  


In [7]:
arr=np.arange(1,25).reshape(2,3,4)
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [10]:
for x in arr:
    for y in x:
        for k in y:
            print(k,end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 

In [11]:
arr=np.arange(10,51,10)
arr

array([10, 20, 30, 40, 50])

In [12]:
for x in np.nditer(arr):
    print(x)

10
20
30
40
50


In [13]:
arr=np.arange(1,13).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [15]:
arr=np.arange(1,25).reshape(2,3,4)
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [16]:
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


In [17]:
arr=np.array([1,2,3,4,5,6,7,8,9])
for x in np.ndenumerate(arr):
    print(x)

((0,), np.int64(1))
((1,), np.int64(2))
((2,), np.int64(3))
((3,), np.int64(4))
((4,), np.int64(5))
((5,), np.int64(6))
((6,), np.int64(7))
((7,), np.int64(8))
((8,), np.int64(9))


In [18]:
for pos,ele in np.ndenumerate(arr):
    print(pos,ele)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6
(6,) 7
(7,) 8
(8,) 9


In [20]:
arr=np.arange(1,13).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
for pos,ele in np.ndenumerate(arr):
    print(pos,ele)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(2, 0) 9
(2, 1) 10
(2, 2) 11
(2, 3) 12
