In [1]:
import numpy as np

In [10]:
arr=np.array([[10,20],[30,40]])
arr

array([[10, 20],
       [30, 40]])

In [11]:
brr=np.array([[1,2],[3,4]])
brr

array([[1, 2],
       [3, 4]])

In [12]:
arr*brr

array([[ 10,  40],
       [ 90, 160]])

In [13]:
arr=np.matrix(arr)

In [14]:
arr

matrix([[10, 20],
        [30, 40]])

In [15]:
brr=np.matrix(brr)
brr

matrix([[1, 2],
        [3, 4]])

In [16]:
arr*brr

matrix([[ 70, 100],
        [150, 220]])

In [17]:
arr=np.array([[10,20],[30,40]])
arr

array([[10, 20],
       [30, 40]])

In [18]:
brr=np.array([[1,2],[3,4]])
brr

array([[1, 2],
       [3, 4]])

In [19]:
np.dot(arr,brr)

array([[ 70, 100],
       [150, 220]])