In [1]:
import numpy as np

In [3]:
arr=np.array([1,2,3,6,5,8,9,7,32,1,5,6,4,2])
arr

array([ 1,  2,  3,  6,  5,  8,  9,  7, 32,  1,  5,  6,  4,  2])

In [4]:
np.sort(arr)

array([ 1,  1,  2,  2,  3,  4,  5,  5,  6,  6,  7,  8,  9, 32])

In [5]:
arr=np.array([[2,1,3],[6,4,5],[8,7,9]])
arr

array([[2, 1, 3],
       [6, 4, 5],
       [8, 7, 9]])

In [6]:
np.sort(arr)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
dtype=[('name','S10'),('height',float),('age',int)]
dtype

[('name', 'S10'), ('height', float), ('age', int)]

In [10]:
values=[('gopie',1.7,45),('vikrant',1.5,38),('satvik',1.8,28)]
values

[('gopie', 1.7, 45), ('vikrant', 1.5, 38), ('satvik', 1.8, 28)]

In [11]:
arr=np.array(values,dtype=dtype)
arr

array([(b'gopie', 1.7, 45), (b'vikrant', 1.5, 38), (b'satvik', 1.8, 28)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

In [12]:
sort_height=np.sort(arr,order='height')

In [13]:
sort_height

array([(b'vikrant', 1.5, 38), (b'gopie', 1.7, 45), (b'satvik', 1.8, 28)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

In [14]:
sort_height=np.sort(arr,order='age')

In [15]:
sort_height

array([(b'satvik', 1.8, 28), (b'vikrant', 1.5, 38), (b'gopie', 1.7, 45)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

In [16]:
sort_age_height=np.sort(arr,order=['age','height'])

In [17]:
sort_age_height

array([(b'satvik', 1.8, 28), (b'vikrant', 1.5, 38), (b'gopie', 1.7, 45)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])