In [2]:
import numpy as np

In [3]:
7/3

2.3333333333333335

In [4]:
7//3

2

In [5]:
arr=np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
print(arr+2)
print(arr-2)
print(arr*2)
print(arr/2)
print(arr//2)
print(arr**2)

[ 3  4  5  6  7  8  9 10 11]
[-1  0  1  2  3  4  5  6  7]
[ 2  4  6  8 10 12 14 16 18]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0 1 1 2 2 3 3 4 4]
[ 1  4  9 16 25 36 49 64 81]


In [9]:
arr=np.arange(1,13).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
print(arr+2)
print()
print(arr-2)
print()
print(arr*2)
print()
print(arr/2)
print()
print(arr//2)
print()
print(arr**2)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]

[[-1  0  1  2]
 [ 3  4  5  6]
 [ 7  8  9 10]]

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

[[0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4. ]
 [4.5 5.  5.5 6. ]]

[[0 1 1 2]
 [2 3 3 4]
 [4 5 5 6]]

[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [11]:
# ZeroDivisionError in python
10/0

ZeroDivisionError: division by zero

In [12]:
# in numpy there is no any ZeroDivisionError
arr=np.zeros((3,4))

In [13]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
arr/0

C:\Users\Hp\AppData\Local\MyTemp\ipykernel_10268\4291252909.py:1: RuntimeWarning: invalid value encountered in divide
  arr/0


array([[nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan]])

In [15]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([11,12,13,14,15])
arr1+arr2

array([12, 14, 16, 18, 20])

In [16]:
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1//arr2)
print(arr1%arr2)


[12 14 16 18 20]
[-10 -10 -10 -10 -10]
[11 24 39 56 75]
[0.09090909 0.16666667 0.23076923 0.28571429 0.33333333]
[0 0 0 0 0]
[1 2 3 4 5]


In [17]:
arr1=np.arange(1,13).reshape(3,4)
arr2=np.arange(1,13).reshape(3,4)

In [18]:
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1//arr2)
print(arr1%arr2)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [19]:
arr1=np.arange(1,13).reshape(3,4)
arr2=np.arange(1,13).reshape(3,4)

In [20]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
np.add(arr1,arr2)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [23]:
np.subtract(arr1,arr2)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [24]:
np.multiply(arr1,arr2)

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [26]:
np.divide(arr1,arr2)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
np.floor_divide(arr1,arr2)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [28]:
np.mod(arr1,arr2)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
np.pow(arr1,arr2)