In [1]:
import numpy as np

In [2]:
arr=np.array([1,5,4,7,8,9,6,3,2,11])
arr

array([ 1,  5,  4,  7,  8,  9,  6,  3,  2, 11])

In [3]:
np.where(arr==2)

(array([8]),)

In [4]:
idx=np.where(arr==2)
arr[idx]

array([2])

In [5]:
arr[arr==2]

array([2])

In [6]:
arr==2

array([False, False, False, False, False, False, False, False,  True,
       False])

In [7]:
arr=np.arange(1,13).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
np.where(arr==11,1,0)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0]])

In [12]:
np.where(arr%2,1,0)

array([[1, 0, 1, 0],
       [1, 0, 1, 0],
       [1, 0, 1, 0]])

In [13]:
arr=np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.searchsorted(arr,8)

np.int64(7)

In [15]:
arr=np.arange(1,13).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
np.searchsorted(arr,8)

ValueError: object too deep for desired array