In [1]:
import numpy as np

In [2]:
arr=np.array([10,20,30,40])  # arr=[10,20,30,40]
brr=np.array([100])          # brr=[100,100,100,100]   
arr+brr                      # arr+brr=[110,120,130,140]

array([110, 120, 130, 140])

In [3]:
arr=np.array([[10,20],[30,40],[50,60]])  
brr=np.array([100,200])          
arr+brr

array([[110, 220],
       [130, 240],
       [150, 260]])

In [4]:
arr=np.array([[10],[20],[30]])  
brr=np.array([10,20,30])          
arr+brr

array([[20, 30, 40],
       [30, 40, 50],
       [40, 50, 60]])