In [1]:
import numpy as np

In [2]:
arr=np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.insert(arr,2,7777)

array([   0,    1, 7777,    2,    3,    4,    5,    6,    7,    8,    9,
         10])

In [4]:
np.insert(arr,[2,6],888)

array([  0,   1, 888,   2,   3,   4,   5, 888,   6,   7,   8,   9,  10])

In [5]:
np.insert(arr,[0],555)

array([555,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [6]:
np.insert(arr,[5],[7878,4545,1212])

array([   0,    1,    2,    3,    4, 7878, 4545, 1212,    5,    6,    7,
          8,    9,   10])

In [7]:
arr=np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.insert(arr,1,100)

array([  1, 100,   2,   3,   4,   5,   6,   7,   8,   9])

In [10]:
np.insert(arr,1,100,axis=0)

array([[  1,   2,   3],
       [100, 100, 100],
       [  4,   5,   6],
       [  7,   8,   9]])

In [11]:
np.insert(arr,1,100,axis=1)

array([[  1, 100,   2,   3],
       [  4, 100,   5,   6],
       [  7, 100,   8,   9]])

In [12]:
a=np.array([[100,200,300],[400,500,600]])
a

array([[100, 200, 300],
       [400, 500, 600]])

In [14]:
np.insert(arr,1,a,axis=0)

array([[  1,   2,   3],
       [100, 200, 300],
       [400, 500, 600],
       [  4,   5,   6],
       [  7,   8,   9]])

In [15]:
np.insert(arr,1,a,axis=1)

array([[  1, 100, 400,   2,   3],
       [  4, 200, 500,   5,   6],
       [  7, 300, 600,   8,   9]])

In [16]:
arr=np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
np.append(arr,100)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 100])

In [18]:
arr=np.array([[10,20],[30,40]])
arr

array([[10, 20],
       [30, 40]])

In [19]:
np.append(arr,[[70,80]],axis=0)

array([[10, 20],
       [30, 40],
       [70, 80]])

In [20]:
np.append(arr,[[70,80]],axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [21]:
np.append(arr,[[70],[80]],axis=1)

array([[10, 20, 70],
       [30, 40, 80]])