In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4])

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr=np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
brr=arr.reshape(3,4)
brr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
crr=np.reshape(arr,(3,4))
crr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [11]:
arr[0]=100

In [12]:
arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12])

In [14]:
brr

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [15]:
crr

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [17]:
arr.reshape((4,3),order='c')

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [ 10,  11,  12]])

In [18]:
arr.reshape((4,3),order='F')

array([[100,   5,   9],
       [  2,   6,  10],
       [  3,   7,  11],
       [  4,   8,  12]])

In [2]:
arr=np.arange(1,10)

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
brr=np.resize(arr,(3,3))
brr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr is brr

False

In [6]:
id(arr)

2841273998800

In [7]:
id(brr)

2841273341904

In [8]:
arr[0]=1000

In [9]:
arr

array([1000,    2,    3,    4,    5,    6,    7,    8,    9])

In [10]:
brr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
brr=np.resize(arr,(5,5))
brr

array([[1000,    2,    3,    4,    5],
       [   6,    7,    8,    9, 1000],
       [   2,    3,    4,    5,    6],
       [   7,    8,    9, 1000,    2],
       [   3,    4,    5,    6,    7]])

In [13]:
arr.resize((6,6))

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [14]:
arr=np.arange(1,10).reshape((3,3))
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr.flatten(order='c')

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr.flatten(order='f')

array([1, 4, 7, 2, 5, 8, 3, 6, 9])