In [1]:
import numpy as np

In [2]:
arr=np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [10]:
arr.shape

(2, 2)

In [3]:
brr=np.array([[5,6],[7,8]])
brr

array([[5, 6],
       [7, 8]])

In [11]:
brr.shape

(2, 2)

In [13]:
crr=np.concatenate((arr,brr))
crr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [14]:
crr.shape

(4, 2)

In [15]:
crr=np.concatenate((arr,brr),axis=1)
crr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [16]:
crr.shape

(2, 4)

In [17]:
crr=np.concatenate((arr,brr),axis=None)
crr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
brr=np.arange(1,16).reshape((5,3))
brr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [20]:
print(arr.shape)
print(brr.shape)

(2, 3)
(5, 3)


In [22]:
np.concatenate((arr,brr))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [24]:
np.concatenate((arr,brr),axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [25]:
np.concatenate((arr,brr),axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 5

In [29]:
arr=np.array([1,2,3,4,5,6,7,8])

In [30]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
brr=np.array([10,20,30,40,50,60,70,80])

In [32]:
brr

array([10, 20, 30, 40, 50, 60, 70, 80])

In [35]:
np.stack((arr,brr))

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [10, 20, 30, 40, 50, 60, 70, 80]])

In [33]:
help(np.stack)

Help on _ArrayFunctionDispatcher in module numpy:

stack(arrays, axis=0, out=None, *, dtype=None, casting='same_kind')
    Join a sequence of arrays along a new axis.

    The ``axis`` parameter specifies the index of the new axis in the
    dimensions of the result. For example, if ``axis=0`` it will be the first
    dimension and if ``axis=-1`` it will be the last dimension.

    Parameters
    ----------
    arrays : sequence of ndarrays
        Each array must have the same shape. In the case of a single ndarray
        array_like input, it will be treated as a sequence of arrays; i.e.,
        each element along the zeroth axis is treated as a separate array.

    axis : int, optional
        The axis in the result array along which the input arrays are stacked.

    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what stack would have returned if no
        out argument were specified.

    dtyp

In [34]:
print(arr.shape)
print(brr.shape)


(8,)
(8,)


In [36]:
np.stack((arr,brr),axis=1)

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30],
       [ 4, 40],
       [ 5, 50],
       [ 6, 60],
       [ 7, 70],
       [ 8, 80]])

In [38]:
arr=np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [39]:
brr=np.array([[5,6],[7,8]])
brr

array([[5, 6],
       [7, 8]])

In [40]:
np.stack((arr,brr),axis=0)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [41]:
np.stack((arr,brr),axis=1)

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [42]:
np.stack((arr,brr),axis=2)

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

In [43]:
arr=np.arange(1,6)
arr

array([1, 2, 3, 4, 5])

In [44]:
brr=np.arange(10,60,10)
brr

array([10, 20, 30, 40, 50])

In [47]:
help(np.vstack)

Help on _ArrayFunctionDispatcher in module numpy:

vstack(tup, *, dtype=None, casting='same_kind')
    Stack arrays in sequence vertically (row wise).

    This is equivalent to concatenation along the first axis after 1-D arrays
    of shape `(N,)` have been reshaped to `(1,N)`. Rebuilds arrays divided by
    `vsplit`.

    This function makes most sense for arrays with up to 3 dimensions. For
    instance, for pixel-data with a height (first axis), width (second axis),
    and r/g/b channels (third axis). The functions `concatenate`, `stack` and
    `block` provide more general stacking and concatenation operations.

    Parameters
    ----------
    tup : sequence of ndarrays
        The arrays must have the same shape along all but the first axis.
        1-D arrays must have the same length. In the case of a single
        array_like input, it will be treated as a sequence of arrays; i.e.,
        each element along the zeroth axis is treated as a separate array.

    dtype : str 

In [48]:
np.vstack((arr,brr))

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [50]:
arr=np.array([[1,2,3,4],[4,5,6,7]])
arr

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [51]:
brr=np.array([[10,20,30,40],[40,50,60,70]])
brr

array([[10, 20, 30, 40],
       [40, 50, 60, 70]])

In [52]:
np.vstack((arr,brr))

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [10, 20, 30, 40],
       [40, 50, 60, 70]])

In [53]:
arr=np.arange(1,6)
arr

array([1, 2, 3, 4, 5])

In [54]:
brr=np.arange(10,60,10)
brr

array([10, 20, 30, 40, 50])

In [55]:
np.hstack((arr,brr))

array([ 1,  2,  3,  4,  5, 10, 20, 30, 40, 50])

In [56]:
arr=np.array([[1,2,3,4],[4,5,6,7]])
arr

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [57]:
brr=np.array([[10,20,30,40],[40,50,60,70]])
brr

array([[10, 20, 30, 40],
       [40, 50, 60, 70]])

In [58]:
np.hstack((arr,brr))

array([[ 1,  2,  3,  4, 10, 20, 30, 40],
       [ 4,  5,  6,  7, 40, 50, 60, 70]])

In [1]:
import numpy as np
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])
result = np.dstack((a, b))
print(result)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
