In [13]:
# creating array using array module
import array
arr=array.array('f',[10,20,30,40,50,60])
print(arr)

array('f', [10.0, 20.0, 30.0, 40.0, 50.0, 60.0])


In [14]:
help(array.array)

Help on class array in module array:

class array(builtins.object)
 |  array(typecode [, initializer]) -> array
 |
 |  Return a new array whose items are restricted by typecode, and
 |  initialized from the optional initializer value, which must be a list,
 |  string or iterable over elements of the appropriate type.
 |
 |  Arrays represent basic values and behave very much like lists, except
 |  the type of objects stored in them is constrained. The type is specified
 |  at object creation time by using a type code, which is a single character.
 |  The following type codes are defined:
 |
 |      Type code   C Type             Minimum size in bytes
 |      'b'         signed integer     1
 |      'B'         unsigned integer   1
 |      'u'         Unicode character  2 (see note)
 |      'h'         signed integer     2
 |      'H'         unsigned integer   2
 |      'i'         signed integer     2
 |      'I'         unsigned integer   2
 |      'l'         signed integer     4
 | 

In [15]:
# creating array using numpy array
import numpy as np
arr=np.array([10,20,30,40,50,60])
print(arr)

[10 20 30 40 50 60]


In [16]:
arr=np.array([10,20,30,40,50,60],dtype=float)
print(arr)

[10. 20. 30. 40. 50. 60.]


In [17]:
arr=np.array([10,20,30,40,50,60],dtype=complex)
print(arr)

[10.+0.j 20.+0.j 30.+0.j 40.+0.j 50.+0.j 60.+0.j]


In [18]:
arr=np.array([10,20,30,40,50,60],dtype=bool)
print(arr)

[ True  True  True  True  True  True]


In [21]:
print("dimension of array ",arr.ndim)
print("data type of array ",arr.dtype)
print("size of array ",arr.size)
print("shape of array ",arr.shape)

dimension of array  1
data type of array  complex128
size of array  6
shape of array  (6,)


In [22]:
l=["ram","raj","shyam","ganpat"]
arr=np.array(l)
print(arr)

['ram' 'raj' 'shyam' 'ganpat']


In [23]:
print("dimension of array ",arr.ndim)
print("data type of array ",arr.dtype)
print("size of array ",arr.size)
print("shape of array ",arr.shape)

dimension of array  1
data type of array  <U6
size of array  4
shape of array  (4,)


In [24]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [25]:
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [26]:
arr=np.arange(10,20)
print(arr)

[10 11 12 13 14 15 16 17 18 19]


In [27]:
arr=np.arange(10,30,3)
print(arr)

[10 13 16 19 22 25 28]


In [28]:
arr=np.arange(10,30,3,dtype=float)
print(arr)

[10. 13. 16. 19. 22. 25. 28.]


In [29]:
arr=np.linspace(1,30,num=20,endpoint=True,retstep=True)
arr

(array([ 1.        ,  2.52631579,  4.05263158,  5.57894737,  7.10526316,
         8.63157895, 10.15789474, 11.68421053, 13.21052632, 14.73684211,
        16.26315789, 17.78947368, 19.31578947, 20.84210526, 22.36842105,
        23.89473684, 25.42105263, 26.94736842, 28.47368421, 30.        ]),
 np.float64(1.5263157894736843))

In [30]:
arr=np.linspace(1,10,num=10,endpoint=False,retstep=True)
arr

(array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1]), np.float64(0.9))

In [32]:
arr=np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
arr=np.zeros((2,3,3))
arr

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [34]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [35]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
np.ones((2,3,4),dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [37]:
np.full(10,fill_value=8)

array([8, 8, 8, 8, 8, 8, 8, 8, 8, 8])

In [38]:
np.full((3,3),fill_value=5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [39]:
np.full((2,3,3),fill_value=5)

array([[[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]]])

In [40]:
# positional argument and keyword argument
def func(a,b,/,c,d):
    print("value of a : ",a)
    print("value of b : ",b)
    print("value of c : ",c)
    print("value of d : ",d)
func(10,20,30,40)

value of a :  10
value of b :  20
value of c :  30
value of d :  40


In [41]:
def func(a,b,/,c,d):
    print("value of a : ",a)
    print("value of b : ",b)
    print("value of c : ",c)
    print("value of d : ",d)
func(a=10,20,30,40)
# before / all must be passed as positional argument

SyntaxError: positional argument follows keyword argument (3570156802.py, line 6)

In [43]:
def func(a,b,/,c,d):
    print("value of a : ",a)
    print("value of b : ",b)
    print("value of c : ",c)
    print("value of d : ",d)
func(10,20,c=30,d=40)
# After / we can pass as positional argument or keyword argument

value of a :  10
value of b :  20
value of c :  30
value of d :  40


In [44]:
def func(a,b,*,c,d):
    print("value of a : ",a)
    print("value of b : ",b)
    print("value of c : ",c)
    print("value of d : ",d)
func(10,20,30,40)
# before * pass as keyword argument 

TypeError: func() takes 2 positional arguments but 4 were given

In [46]:
def func(a,b,*,c,d):
    print("value of a : ",a)
    print("value of b : ",b)
    print("value of c : ",c)
    print("value of d : ",d)
func(a=10,b=20,c=30,d=40)
# before * pass as keyword argument and once you start giving as keyword argument then give as keyword argumant only noy positional argument

value of a :  10
value of b :  20
value of c :  30
value of d :  40


In [ ]:
def func(a,b,*,c,d):
    print("value of a : ",a)
    print("value of b : ",b)
    print("value of c : ",c)
    print("value of d : ",d)
func(a=10,b=20,c=30,d=40)
# before * pass as keyword argument and once you start giving as keyword argument then give as keyword argumant only noy positional argument

In [47]:
def func(a,b,*,c,d):
    print("value of a : ",a)
    print("value of b : ",b)
    print("value of c : ",c)
    print("value of d : ",d)
func(10,20,a=30,b=40)

TypeError: func() got multiple values for argument 'a'

In [48]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
np.eye(3,3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [50]:
np.eye(3,3,k=2)

array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [51]:
np.eye(3,3,k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [52]:
np.eye(3,3,k=-2)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.]])

In [53]:
np.eye(4,k=0)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [54]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [55]:
np.identity(5,dtype=float)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [56]:
# diag() it will create the array of given diagonal elements
# diag() it will exract diagnol elements from give array
arr=np.array([10,20,30])
np.diag(arr)

array([[10,  0,  0],
       [ 0, 20,  0],
       [ 0,  0, 30]])

In [58]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr)
np.diag(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


array([10, 50, 90])

In [59]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr)
np.diag(arr,k=0)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


array([10, 50, 90])

In [60]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr)
np.diag(arr,k=1)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


array([20, 60])

In [61]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr)
np.diag(arr,k=2)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


array([30])

In [62]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr)
np.diag(arr,k=-1)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


array([40, 80])

In [64]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr)
np.diag(arr,k=-2)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


array([70])

In [66]:
np.empty(15)

array([4.67296746e-307, 1.69121096e-306, 6.23058707e-307, 2.22522597e-306,
       1.33511969e-306, 1.37962320e-306, 9.34604358e-307, 9.79101082e-307,
       1.78020576e-306, 1.69119873e-306, 2.22522868e-306, 1.24611809e-306,
       8.06632139e-308, 1.60221208e-306, 2.29178686e-312])

In [65]:
np.empty((3,3))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [6.23058707e-307, 2.22526399e-307, 6.23053614e-307],
       [7.56592338e-307, 5.33590898e-322, 0.00000000e+000]])

In [1]:
import numpy as np
from numpy import random

In [3]:
arr=random.randint(10,20,size=10)
print(arr)

[18 12 18 15 15 10 11 11 17 11]


In [4]:
arr=random.randint(15,50,size=(3,4))
print(arr)

[[16 20 41 39]
 [21 41 45 22]
 [32 21 49 33]]


In [7]:
arr=random.randint(15,50,size=(4,4))
print(arr)

[[26 45 17 43]
 [19 43 15 25]
 [19 37 15 34]
 [22 23 16 23]]


In [10]:
arr1=random.randint(10,50,(10))
print(arr1)
arr2=arr1.astype(float)
print(arr2)

[40 18 18 33 35 19 33 42 48 20]
[40. 18. 18. 33. 35. 19. 33. 42. 48. 20.]


In [11]:
arr=random.rand()
arr

0.016703358675681845

In [12]:
arr=random.rand(10)
arr

array([0.59347243, 0.57439261, 0.70114592, 0.40306796, 0.14157027,
       0.90051173, 0.72070066, 0.05744087, 0.46375339, 0.89723203])

In [13]:
arr=random.rand(10,3)
arr

array([[0.2042951 , 0.89261132, 0.52877915],
       [0.15339181, 0.30249016, 0.51652302],
       [0.74778722, 0.81500117, 0.71346149],
       [0.29589146, 0.34743986, 0.84134015],
       [0.21064683, 0.87189399, 0.25214139],
       [0.6163018 , 0.62917948, 0.71470897],
       [0.59431136, 0.16321048, 0.86714695],
       [0.33530289, 0.46543206, 0.08810736],
       [0.37475436, 0.38583573, 0.0071816 ],
       [0.34564473, 0.77300691, 0.35675918]])

In [14]:
arr=random.rand(10,2,3)
arr

array([[[0.28694522, 0.2390604 , 0.12731297],
        [0.57653677, 0.35157613, 0.34256402]],

       [[0.19596448, 0.43229954, 0.26202277],
        [0.84645896, 0.57261783, 0.27395674]],

       [[0.03022012, 0.21607301, 0.3654377 ],
        [0.40192263, 0.06907789, 0.92658254]],

       [[0.24794049, 0.37676332, 0.83449064],
        [0.56796428, 0.44798518, 0.64739732]],

       [[0.74884622, 0.55603495, 0.93452717],
        [0.03769833, 0.26335769, 0.56495461]],

       [[0.81089647, 0.73569175, 0.32834466],
        [0.36271063, 0.40993051, 0.38857562]],

       [[0.35578265, 0.32291928, 0.41477948],
        [0.29972518, 0.9509104 , 0.75418897]],

       [[0.05092348, 0.2004241 , 0.0060433 ],
        [0.80191543, 0.28097284, 0.70966177]],

       [[0.02256627, 0.8805028 , 0.54308136],
        [0.34230547, 0.24630272, 0.76454791]],

       [[0.15622899, 0.56118351, 0.5405248 ],
        [0.23509663, 0.94546612, 0.98086611]]])

In [15]:
np.random.uniform()

0.15763911693261223

In [17]:
np.random.uniform(10,20,5)

array([15.88934163, 13.8142381 , 18.26750023, 15.93138157, 11.29376615])

In [18]:
np.random.uniform(10,20,(3,5))

array([[14.7414537 , 10.43426028, 10.68996704, 12.72563106, 11.00330833],
       [16.88701757, 16.77696571, 11.71846163, 10.13147562, 18.37615663],
       [10.85358671, 10.91108937, 11.59254333, 19.64780208, 16.03363256]])

In [19]:
np.random.randn(10)

array([-0.4341623 ,  0.19284782,  0.27484781, -1.27582012, -0.56613155,
        0.29014643,  0.15004232, -1.55164739,  0.13411137,  0.80019908])

In [22]:
np.random.randn(3,5,2)

array([[[ 0.24424063,  0.52946127],
        [ 0.55633739,  1.09876572],
        [-0.50426337, -0.22752873],
        [-0.10093321,  0.21023685],
        [ 0.86858526,  0.08671763]],

       [[-0.05562373, -0.1025389 ],
        [-0.54346789, -0.5018523 ],
        [ 0.11935508,  1.97104539],
        [-0.18110929,  0.29096406],
        [ 1.78399519,  1.36655197]],

       [[-0.29920076,  0.39439809],
        [ 1.45743934,  0.06921919],
        [ 1.15643539, -0.83088115],
        [-0.99171132, -1.09182917],
        [ 0.25961846, -0.12246428]]])

In [24]:
arr=np.random.normal(10,5,10)

In [25]:
print(arr.mean())
print(arr.var())
print(arr.std())

8.060270316380095
27.915605377346246
5.283522061782864


In [27]:
arr=np.arange(1,10)

In [28]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.random.shuffle(arr)

In [30]:
arr

array([7, 1, 2, 5, 3, 8, 4, 9, 6])

In [48]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [49]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
np.random.shuffle(arr)