In [1]:
import numpy as np

#### 1D Array Indexing

In [2]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [3]:
arr[0]

np.int64(1)

In [4]:
arr[-1]

np.int64(6)

#### 2D Array Indexing

In [5]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr[0][2]

np.int64(3)

In [8]:
arr[-3][-3]

np.int64(1)

In [9]:
arr[0][-1]

np.int64(3)

#### 3D Array Indexing

In [10]:
arr=np.arange(1,19).reshape(2,3,3)
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [11]:
arr[1][1][1]

np.int64(14)

In [12]:
arr[-1][-2][-2]

np.int64(14)

In [14]:
arr[-1][0][0]

np.int64(10)

#### 4D Array Indexing

In [15]:
arr=np.arange(1,121).reshape(2,3,4,5)
arr

array([[[[  1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10],
         [ 11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20]],

        [[ 21,  22,  23,  24,  25],
         [ 26,  27,  28,  29,  30],
         [ 31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40]],

        [[ 41,  42,  43,  44,  45],
         [ 46,  47,  48,  49,  50],
         [ 51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60]]],


       [[[ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70],
         [ 71,  72,  73,  74,  75],
         [ 76,  77,  78,  79,  80]],

        [[ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90],
         [ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100]],

        [[101, 102, 103, 104, 105],
         [106, 107, 108, 109, 110],
         [111, 112, 113, 114, 115],
         [116, 117, 118, 119, 120]]]])

In [16]:
arr[1][1][3][4]

np.int64(100)

In [17]:
np.where(arr==115)

(array([1]), array([2]), array([2]), array([4]))

#### 1D Array Slicing

In [19]:
arr=np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr[0:5]

array([1, 2, 3, 4, 5])

In [21]:
arr[1:-2]

array([2, 3, 4, 5, 6, 7])

In [22]:
arr[-6:-3]

array([4, 5, 6])

In [23]:
arr[:100]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 2D Array Slicing

In [1]:
import numpy as np

In [2]:
arr=np.array([[10,20],[30,40],[50,60]])
arr

array([[10, 20],
       [30, 40],
       [50, 60]])

In [3]:
arr[:,:]

array([[10, 20],
       [30, 40],
       [50, 60]])

In [4]:
arr[::-1,::-1]

array([[60, 50],
       [40, 30],
       [20, 10]])

In [5]:
arr[0:2,0:]

array([[10, 20],
       [30, 40]])

In [6]:
arr[1:,:]

array([[30, 40],
       [50, 60]])

In [7]:
arr[:,0]

array([10, 30, 50])

In [8]:
arr[0,0]

np.int64(10)

#### 3D Slicing

In [10]:
arr=np.arange(1,25).reshape(2,3,4)
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [11]:
arr[0,0:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
arr[:,0:2,]

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20]]])

In [13]:
arr[:,0:2,0:2]

array([[[ 1,  2],
        [ 5,  6]],

       [[13, 14],
        [17, 18]]])

#### Advance Indexing

In [14]:
arr=np.array([10,20,30,40,50,60,70,80,90,100])
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [15]:
index=np.array([1,3,7,6])
arr[index]

array([20, 40, 80, 70])

In [16]:
index=[1,3,7,6]
arr[index]

array([20, 40, 80, 70])

In [17]:
arr=np.arange(1,17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [18]:
# (0,0) (0,2) (1,1) (1,3) (2,2) (3,0) (3,2)
row=[0,0,1,1,2,3,3]
col=[0,2,1,3,2,0,2]
arr[row,col]

array([ 1,  3,  6,  8, 11, 13, 15])

In [19]:
arr=np.arange(1,25).reshape(2,3,4)
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [20]:
# 6 (0,1,1)  22 (1,2,1)
i=[0,1]
j=[1,2]
k=[1,1]
arr[i,j,k]

array([ 6, 22])

#### Condition based selection

In [21]:
arr=np.array([10,20,30,40,50,60,70,80,90])
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [23]:
bool_arr=[True,False,True,False,True,True,False,True,False]
arr[bool_arr]

array([10, 30, 50, 60, 80])

In [24]:
bool_arr=arr>50
arr[bool_arr]

array([60, 70, 80, 90])

In [25]:
arr[arr<50]

array([10, 20, 30, 40])

In [26]:
arr=np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [2]:
arr=np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [3]:
bool_arr=np.logical_and(arr%2==0,arr%10==0)
bool_arr

array([[False, False, False, False, False],
       [False, False, False, False,  True],
       [False, False, False, False, False],
       [False, False, False, False,  True],
       [False, False, False, False, False]])

In [4]:
arr[bool_arr]

array([10, 20])

In [6]:
arr[(arr%2==0) & (arr%5==0)]

array([10, 20])

In [8]:
bool_arr=np.logical_or(arr%2==0,arr%3==0)
bool_arr

array([[False,  True,  True,  True, False],
       [ True, False,  True,  True,  True],
       [False,  True, False,  True,  True],
       [ True, False,  True, False,  True],
       [ True,  True, False,  True, False]])

In [9]:
arr[bool_arr]

array([ 2,  3,  4,  6,  8,  9, 10, 12, 14, 15, 16, 18, 20, 21, 22, 24])

In [11]:
arr[(arr%2==0) | (arr%3==0)]

array([ 2,  3,  4,  6,  8,  9, 10, 12, 14, 15, 16, 18, 20, 21, 22, 24])