In [1]:
import numpy as np

In [3]:
arr=np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.delete(arr,2)

array([1, 2, 4, 5, 6, 7, 8, 9])

In [5]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.delete(arr,[2,5,7])

array([1, 2, 4, 5, 7, 9])

In [7]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr=np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.delete(arr,1,axis=0)

array([[1, 2, 3],
       [7, 8, 9]])

In [10]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.delete(arr,1,axis=1)

array([[1, 3],
       [4, 6],
       [7, 9]])

In [12]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.delete(arr,1)

array([1, 3, 4, 5, 6, 7, 8, 9])