In [1]:
import numpy as np

In [2]:
arr=np.array([10,20,30,40,50,60])
print(arr)

[10 20 30 40 50 60]


In [4]:
brr=arr.view()
brr

array([10, 20, 30, 40, 50, 60])

In [6]:
arr[0]=777
print(arr)
print(brr)

[777  20  30  40  50  60]
[777  20  30  40  50  60]


In [7]:
brr[2]=1000
print(arr)
print(brr)

[ 777   20 1000   40   50   60]
[ 777   20 1000   40   50   60]


In [8]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [9]:
brr=arr.copy()
brr

array([1, 2, 3, 4, 5, 6])

In [10]:
arr[0]=888
print(arr)
print(brr)

[888   2   3   4   5   6]
[1 2 3 4 5 6]


In [11]:
brr[1]=1000
print(arr)
print(brr)

[888   2   3   4   5   6]
[   1 1000    3    4    5    6]
