In [1]:
import numpy as np

In [2]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.split(arr,2)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [4]:
arr=np.arange(1,25).reshape(6,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [10]:
np.split(arr,2,axis=0)

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])]

In [11]:
arr=np.arange(1,5).reshape(2,2)
arr

array([[1, 2],
       [3, 4]])

In [12]:
np.split(arr,2,axis=0)

[array([[1, 2]]), array([[3, 4]])]

In [13]:
np.split(arr,2,axis=1)


[array([[1],
        [3]]),
 array([[2],
        [4]])]

In [14]:
arr=np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
np.split(arr,[1,4,8])

[array([0]), array([1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10])]

In [22]:
arr=np.arange(0,24)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [23]:
arr.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [25]:
np.split(arr,[1,2],axis=0)

[array([0]),
 array([1]),
 array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23])]

In [26]:
arr=np.arange(1,13).reshape(6,2)
arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [27]:
np.split(arr,[3,4])

[array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

In [36]:
arr=np.arange(0,24).reshape(4,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [38]:
np.split(arr,[1,3,4],axis=1)

[array([[ 0],
        [ 6],
        [12],
        [18]]),
 array([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20]]),
 array([[ 3],
        [ 9],
        [15],
        [21]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23]])]

In [39]:
arr=np.arange(1,13).reshape(2,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [41]:
np.vsplit(arr,[1,2,4])

[array([[1, 2, 3, 4, 5, 6]]),
 array([[ 7,  8,  9, 10, 11, 12]]),
 array([], shape=(0, 6), dtype=int64),
 array([], shape=(0, 6), dtype=int64)]

In [42]:
arr=np.arange(1,11)

In [43]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
np.hsplit(arr,2)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [2]:
arr=np.arange(1,13).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
np.hsplit(arr,[1,2])

[array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]

In [4]:
arr=np.arange(1,25).reshape(2,3,4)
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [5]:
np.dsplit(arr,[1,3])

[array([[[ 1],
         [ 5],
         [ 9]],
 
        [[13],
         [17],
         [21]]]),
 array([[[ 2,  3],
         [ 6,  7],
         [10, 11]],
 
        [[14, 15],
         [18, 19],
         [22, 23]]]),
 array([[[ 4],
         [ 8],
         [12]],
 
        [[16],
         [20],
         [24]]])]